# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/ParticleSystem2SDL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/ParticleSystem2SDL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/ParticleSystem2SDL/CMakeFiles /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/ParticleSystem2SDL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/ParticleSystem2SDL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ParticleSystem2SDL

# Build rule for target.
ParticleSystem2SDL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParticleSystem2SDL
.PHONY : ParticleSystem2SDL

# fast build rule for target.
ParticleSystem2SDL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/build
.PHONY : ParticleSystem2SDL/fast

emitter.o: emitter.cpp.o
.PHONY : emitter.o

# target to build an object file
emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/emitter.cpp.o
.PHONY : emitter.cpp.o

emitter.i: emitter.cpp.i
.PHONY : emitter.i

# target to preprocess a source file
emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/emitter.cpp.i
.PHONY : emitter.cpp.i

emitter.s: emitter.cpp.s
.PHONY : emitter.s

# target to generate assembly for a file
emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/emitter.cpp.s
.PHONY : emitter.cpp.s

engine.o: engine.cpp.o
.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i
.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/engine.cpp.s
.PHONY : engine.cpp.s

input.o: input.cpp.o
.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i
.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s
.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/input.cpp.s
.PHONY : input.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/main.cpp.s
.PHONY : main.cpp.s

particle.o: particle.cpp.o
.PHONY : particle.o

# target to build an object file
particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particle.cpp.o
.PHONY : particle.cpp.o

particle.i: particle.cpp.i
.PHONY : particle.i

# target to preprocess a source file
particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particle.cpp.i
.PHONY : particle.cpp.i

particle.s: particle.cpp.s
.PHONY : particle.s

# target to generate assembly for a file
particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particle.cpp.s
.PHONY : particle.cpp.s

particlepool.o: particlepool.cpp.o
.PHONY : particlepool.o

# target to build an object file
particlepool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particlepool.cpp.o
.PHONY : particlepool.cpp.o

particlepool.i: particlepool.cpp.i
.PHONY : particlepool.i

# target to preprocess a source file
particlepool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particlepool.cpp.i
.PHONY : particlepool.cpp.i

particlepool.s: particlepool.cpp.s
.PHONY : particlepool.s

# target to generate assembly for a file
particlepool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particlepool.cpp.s
.PHONY : particlepool.cpp.s

particlesystem.o: particlesystem.cpp.o
.PHONY : particlesystem.o

# target to build an object file
particlesystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particlesystem.cpp.o
.PHONY : particlesystem.cpp.o

particlesystem.i: particlesystem.cpp.i
.PHONY : particlesystem.i

# target to preprocess a source file
particlesystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particlesystem.cpp.i
.PHONY : particlesystem.cpp.i

particlesystem.s: particlesystem.cpp.s
.PHONY : particlesystem.s

# target to generate assembly for a file
particlesystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/particlesystem.cpp.s
.PHONY : particlesystem.cpp.s

perftimer.o: perftimer.cpp.o
.PHONY : perftimer.o

# target to build an object file
perftimer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/perftimer.cpp.o
.PHONY : perftimer.cpp.o

perftimer.i: perftimer.cpp.i
.PHONY : perftimer.i

# target to preprocess a source file
perftimer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/perftimer.cpp.i
.PHONY : perftimer.cpp.i

perftimer.s: perftimer.cpp.s
.PHONY : perftimer.s

# target to generate assembly for a file
perftimer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/perftimer.cpp.s
.PHONY : perftimer.cpp.s

render.o: render.cpp.o
.PHONY : render.o

# target to build an object file
render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/render.cpp.o
.PHONY : render.cpp.o

render.i: render.cpp.i
.PHONY : render.i

# target to preprocess a source file
render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/render.cpp.i
.PHONY : render.cpp.i

render.s: render.cpp.s
.PHONY : render.s

# target to generate assembly for a file
render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/render.cpp.s
.PHONY : render.cpp.s

scene.o: scene.cpp.o
.PHONY : scene.o

# target to build an object file
scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/scene.cpp.o
.PHONY : scene.cpp.o

scene.i: scene.cpp.i
.PHONY : scene.i

# target to preprocess a source file
scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/scene.cpp.i
.PHONY : scene.cpp.i

scene.s: scene.cpp.s
.PHONY : scene.s

# target to generate assembly for a file
scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/scene.cpp.s
.PHONY : scene.cpp.s

texture.o: texture.cpp.o
.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i
.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/texture.cpp.s
.PHONY : texture.cpp.s

timer.o: timer.cpp.o
.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i
.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s
.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/timer.cpp.s
.PHONY : timer.cpp.s

window.o: window.cpp.o
.PHONY : window.o

# target to build an object file
window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/window.cpp.o
.PHONY : window.cpp.o

window.i: window.cpp.i
.PHONY : window.i

# target to preprocess a source file
window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/window.cpp.i
.PHONY : window.cpp.i

window.s: window.cpp.s
.PHONY : window.s

# target to generate assembly for a file
window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleSystem2SDL.dir/build.make CMakeFiles/ParticleSystem2SDL.dir/window.cpp.s
.PHONY : window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ParticleSystem2SDL"
	@echo "... emitter.o"
	@echo "... emitter.i"
	@echo "... emitter.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... particle.o"
	@echo "... particle.i"
	@echo "... particle.s"
	@echo "... particlepool.o"
	@echo "... particlepool.i"
	@echo "... particlepool.s"
	@echo "... particlesystem.o"
	@echo "... particlesystem.i"
	@echo "... particlesystem.s"
	@echo "... perftimer.o"
	@echo "... perftimer.i"
	@echo "... perftimer.s"
	@echo "... render.o"
	@echo "... render.i"
	@echo "... render.s"
	@echo "... scene.o"
	@echo "... scene.i"
	@echo "... scene.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

